### ISSUE TITLE
Fix code scanning alert - Unexpected character ('}' (code 125)): was expecting double-quote to start field name

### ISSUE THREAD

**Issue by speedyfriend67** [speedyfriend67/Swifile-FileManager#10]
Tracking issue for:
- [ ] https://github.com/speedyfriend67/Swifile-FileManager/security/code-scanning/105

**Comment by lebao3105** [comment]
Since it's about VSCode workspace settings, close this project.

**Comment by speedyfriend67** [comment]
was this for vscode only? i thought it was xcodeproj collaboration

**Comment by speedyfriend67** [comment]
anyways alright

**Comment by lebao3105** [comment]
> was this for vscode only? i thought it was xcodeproj collaboration

The error clearly shows it

**Comment by speedyfriend67** [comment]
Hi1144003752978829455

**Comment by lebao3105** [comment]
What the heck is going on here

**Comment by speedyfriend67** [comment]
Hiundefined

**Comment by speedyfriend67** [comment]
> Hiundefined

This one wasn’t mine 
![IMG_8988](https://github.com/speedyfriend67/Swifile-FileManager/assets/82425907/099fad5c-a38c-4cd9-a355-1138ad381609)
